<?php

namespace haqqi\metronic\controllers;

use haqqi\metronic\assets\core\VersionAsset;
use yii\web\Controller;

class AuthController extends Controller
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $this->layout = '@haqqi/metronic/views/layouts/main';
    }
    
    public function actionLoginV1() {
        VersionAsset::noPublish(); // no need to publish version asset, but we need the other
        
        return $this->render('login-v1');
    }
}
