<?php

namespace haqqi\metronic\controllers;


use yii\web\Controller;

class DashboardController extends Controller
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $this->layout = '@haqqi/metronic/views/layouts/main';
    }

    public function actionIndex() {
        return $this->render('index');
    }
}